services:
  api-send-email:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - ./log:/app/log
      - ./database:/app/database
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    container_name: api-send-email
